@startuml
left to right direction

title **Use Case Diagram**

actor U as "User"

rectangle DB as "Database"

rectangle "DatabaseOutput" {

    usecase UC1 as "Create report for population of countries"
    usecase UC2 as "Create report for population of cities"
    usecase UC3 as "Create report for population of capital cities"
    usecase UC4 as "Create report for population of cities and non citites"
    usecase UC5 as "Create report for spoken languages"
    usecase PRINT as "Print report"

    U -- UC1
    U -- UC2
    U -- UC3
    U -- UC4
    U -- UC5

    UC1 ..> PRINT : extend
    UC2 ..> PRINT : extend
    UC3 ..> PRINT : extend
    UC4 ..> PRINT : extend
    UC5 ..> PRINT : extend

    UC1 -- DB
    UC2 -- DB
    UC3 -- DB
    UC4 -- DB
    UC5 -- DB
}

@enduml